# Generated by Django 3.0.2 on 2020-05-02 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='detail',
            new_name='details',
        ),
    ]
