# Generated by Django 3.0.2 on 2020-05-02 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20200502_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='details',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
