# Generated by Django 3.0.2 on 2020-05-02 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20200502_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='verify_email',
            field=models.BooleanField(default=False, null=True, verbose_name='email'),
        ),
    ]
