# Generated by Django 3.0.2 on 2020-05-02 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_auto_20200503_0018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='verify_email',
        ),
    ]
