# Generated by Django 3.0.2 on 2020-05-02 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='feedback',
            new_name='feeds',
        ),
    ]
